#!/bin/bash

### BEGIN INIT INFO
# Provides:	  avancedb
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the avancedb server
# Description:       starts the avancedb database and web server
### END INIT INFO

NAME=avancedb
DESC=$NAME

ROOT_DIR=/usr/local/${NAME}/
LOG_DIR=${ROOT_DIR}var/log/${NAME}/
LOG_NAME=${LOG_DIR}${NAME}.log
DAEMON=${ROOT_DIR}${NAME}

test -x $DAEMON || exit 1

. /lib/init/vars.sh
. /lib/lsb/init-functions

case "$1" in
  start)
    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
    pushd ${ROOT_DIR}
    ./avancedb > ${LOG_NAME} & 
    popd
    ;;
  stop)
    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
    pkill avancedb
    ;;
  *)
    echo "Usage: ${DAEMON_NAME} {start|stop}"
    exit 1
    ;;
esac

exit 0
